### ISSUE TITLE
Transfer error when wrapping filename in quotes

### ISSUE THREAD

**Issue by rschapman** [nils-werner/zget#4]
I tried transferring a file with weird name. Some *nix programs will let you wrap the filename in quotes rather than escape different parts. When I tried this it threw an error.

user-mbp:Documents User$ zget "namebench_ 2015-07-08 22_37_46.pdf"
Peer found. Downloading...
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.4/site-packages/zeroconf.py", line 1063, in run
    handler(self.zc)
  File "/usr/local/lib/python3.4/site-packages/zeroconf.py", line 1014, in <lambda>
    state_change=state_change,
  File "/usr/local/lib/python3.4/site-packages/zeroconf.py", line 931, in fire
    h(**kwargs)
  File "/usr/local/lib/python3.4/site-packages/zeroconf.py", line 989, in on_change
    listener.add_service(*args)
  File "/usr/local/lib/python3.4/site-packages/zget/get.py", line 38, in add_service
    urllib.urlretrieve(url, output)
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 186, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 161, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 463, in open
    response = self._open(req, data)
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 481, in _open
    '_open', req)
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 441, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 1210, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 1185, in do_open
    r = h.getresponse()
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/http/client.py", line 1171, in getresponse
    response.begin()
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/http/client.py", line 351, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/http/client.py", line 333, in _read_status
    raise BadStatusLine(line)
http.client.BadStatusLine: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"

**Comment by nils-werner** [comment]
Thanks for the report. It had to do with `urllib.urlretrieve(url, output)` apparently requesting unescaped URLs under Python 3. It's fixed in version 0.7.
