### ISSUE TITLE
Would like to get this running under Python 2.6, if possible

### ISSUE THREAD

**Issue by fyngyrz** [nils-werner/zget#9]
If you're willing to look at Python 2.6 favorably:

This fails with an exception under `OS X 10.6.8` & `Python 2.6`:

    pip install --user zget

Would you please provide installation directions?

Thank you.

Here's the failure, if you are interested:

```
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.6/site-packages/pip-7.1.2-py2.6.egg/pip/basecommand.py", line 211, in main
    status = self.run(options, args)
  File "/Library/Python/2.6/site-packages/pip-7.1.2-py2.6.egg/pip/commands/install.py", line 294, in run
    requirement_set.prepare_files(finder)
  File "/Library/Python/2.6/site-packages/pip-7.1.2-py2.6.egg/pip/req/req_set.py", line 334, in prepare_files
    functools.partial(self._prepare_file, finder))
  File "/Library/Python/2.6/site-packages/pip-7.1.2-py2.6.egg/pip/req/req_set.py", line 321, in _walk_req_to_install
    more_reqs = handler(req_to_install)
  File "/Library/Python/2.6/site-packages/pip-7.1.2-py2.6.egg/pip/req/req_set.py", line 461, in _prepare_file
    req_to_install.populate_link(finder, self.upgrade)
  File "/Library/Python/2.6/site-packages/pip-7.1.2-py2.6.egg/pip/req/req_install.py", line 250, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/Library/Python/2.6/site-packages/pip-7.1.2-py2.6.egg/pip/index.py", line 486, in find_requirement
    all_versions = self._find_all_versions(req.name)
  File "/Library/Python/2.6/site-packages/pip-7.1.2-py2.6.egg/pip/index.py", line 404, in _find_all_versions
    index_locations = self._get_index_urls_locations(project_name)
  File "/Library/Python/2.6/site-packages/pip-7.1.2-py2.6.egg/pip/index.py", line 378, in _get_index_urls_locations
    page = self._get_page(main_index_url)
  File "/Library/Python/2.6/site-packages/pip-7.1.2-py2.6.egg/pip/index.py", line 818, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/Library/Python/2.6/site-packages/pip-7.1.2-py2.6.egg/pip/index.py", line 928, in get_page
    "Cache-Control": "max-age=600",
  File "/Library/Python/2.6/site-packages/pip-7.1.2-py2.6.egg/pip/_vendor/requests/sessions.py", line 477, in get
    return self.request('GET', url, **kwargs)
  File "/Library/Python/2.6/site-packages/pip-7.1.2-py2.6.egg/pip/download.py", line 373, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/Library/Python/2.6/site-packages/pip-7.1.2-py2.6.egg/pip/_vendor/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.6/site-packages/pip-7.1.2-py2.6.egg/pip/_vendor/requests/sessions.py", line 605, in send
    r.content
  File "/Library/Python/2.6/site-packages/pip-7.1.2-py2.6.egg/pip/_vendor/requests/models.py", line 750, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/Library/Python/2.6/site-packages/pip-7.1.2-py2.6.egg/pip/_vendor/requests/models.py", line 673, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/Library/Python/2.6/site-packages/pip-7.1.2-py2.6.egg/pip/_vendor/requests/packages/urllib3/response.py", line 307, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/Library/Python/2.6/site-packages/pip-7.1.2-py2.6.egg/pip/_vendor/requests/packages/urllib3/response.py", line 243, in read
    data = self._fp.read(amt)
  File "/Library/Python/2.6/site-packages/pip-7.1.2-py2.6.egg/pip/_vendor/cachecontrol/filewrapper.py", line 54, in read
    self.__callback(self.__buf.getvalue())
  File "/Library/Python/2.6/site-packages/pip-7.1.2-py2.6.egg/pip/_vendor/cachecontrol/controller.py", line 244, in cache_response
    self.serializer.dumps(request, response, body=body),
  File "/Library/Python/2.6/site-packages/pip-7.1.2-py2.6.egg/pip/download.py", line 276, in set
    return super(SafeFileCache, self).set(*args, **kwargs)
  File "/Library/Python/2.6/site-packages/pip-7.1.2-py2.6.egg/pip/_vendor/cachecontrol/caches/file_cache.py", line 99, in set
    with self.lock_class(name) as lock:
  File "/Library/Python/2.6/site-packages/pip-7.1.2-py2.6.egg/pip/_vendor/lockfile/mkdirlockfile.py", line 18, in __init__
    LockBase.__init__(self, path, threaded, timeout)
  File "/Library/Python/2.6/site-packages/pip-7.1.2-py2.6.egg/pip/_vendor/lockfile/__init__.py", line 173, in __init__
    self.tname = "-%x" % (ident & 0xffffffff)
TypeError: unsupported operand type(s) for &: 'NoneType' and 'long'
```

**Comment by nils-werner** [comment]
Looks more like an error within pip, specifically lockfile within pip (they bundle their dependencies). pip 7.1.2 was using lockfile 0.10.2 while the most recent version of pip is using 0.12.2.

Try upgrading to the latest version of pip and try again.
